sudo: required
language: node_js
node_js:
  - stable
addons:
  chrome: stable
cache:
  directories:
    - node_modules
branches:
  only:
    - src
    - /^greenkeeper/.*$/

# Preparate to install
before_install:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo TRAVIS_BRANCH = $TRAVIS_BRANCH

install:
  - npm i
  - npm i coveralls

# Lint the code
# Build a source code
before_script:
  - npm run lint
  - npm run build

# Run tests
# Generate coverage info and deploy it to coveralls.io
# Copy ci files for prevent errors when deploying
script:
  - npm run travis:e2e
  - npm run travis:test
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cp .travis.yml ./dist
  - cp -r .circleci ./dist

# Sync github repo with gitlab
# Build docker image and push it to hub
after_success:
  - git remote add gitlab https://gitlab-ci-token:$GITLAB_TOKEN@gitlab.com/mpgp/mpgp.github.io.git
  - git push gitlab src
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --rm --no-cache -t mpgp129/mpgpspec -f ./docker/Dockerfile .
  - docker push mpgp129/mpgpspec

# Deploy dist folder to master(gh-pages) branch
# https://github.com/settings/tokens
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target-branch: master
  email: torvalds@linux-foundation.org
  name: Linus Torvalds
  on:
    branch: "src"