sudo: required
language: node_js
node_js:
  - stable
addons:
  chrome: stable
cache:
  directories:
    - spec/node_modules
branches:
  only:
    - src

before_install:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd spec
install:
  - npm i
  - npm i coveralls
before_script:
  - npm run lint
  - npm run build
script:
  - npm run travis:e2e
  - npm run travis:test

# coveralls.io
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
  - cd ..
  - cp .travis.yml ./dist
  - cp -r .circleci ./dist
  - git remote add gitlab https://gitlab-ci-token:$GITLAB_TOKEN@gitlab.com/mpgp/mpgp.github.io.git
  - git push gitlab src

deploy:
  provider: pages
  skip_cleanup: true
  
  # https://github.com/settings/tokens
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target-branch: master
  email: torvalds@linux-foundation.org
  name: Linus Torvalds
  on:
    branch: "src"
