sudo: required
language: node_js
node_js:
  - stable
addons:
  chrome: stable
cache:
  directories:
    - node_modules
branches:
  only:
    - src
    - /^greenkeeper/.*$/

before_install:
  - bash scripts/ci/1_before_install.sh

install:
  - bash scripts/ci/2_install.sh

before_script:
  - bash scripts/ci/3_before_script.sh

script:
  - bash scripts/ci/4_script.sh

deploy:
  - on:
      branch: "src"
    provider: script
    skip_cleanup: true
    script:
      - BRANCH=$TRAVIS_BRANCH DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD GITLAB_TOKEN=$GITLAB_TOKEN bash scripts/ci/5_deploy.sh

# Deploy dist folder to master(gh-pages) branch
# https://github.com/settings/tokens
  - on:
      branch: "src"
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    target-branch: master
    email: torvalds@linux-foundation.org
    name: Linus Torvalds